// <auto-generated />
using HousingApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HousingApi.Migrations
{
    [DbContext(typeof(HousingContext))]
    [Migration("20240612210022_AddApplicationSubmissions")]
    partial class AddApplicationSubmissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HousingApi.Models.ApplicationSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ApplicationSubmissions");
                });

            modelBuilder.Entity("HousingApi.Models.HousingLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableUnits")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<bool>("Laundry")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Photo")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<bool>("Wifi")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("HousingLocations");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            AvailableUnits = 4,
                            City = "Chicago",
                            Laundry = true,
                            Name = "Acme Fresh Start Housing",
                            Photo = "https://angular.io/assets/images/tutorials/faa/bernard-hermant-CLKGGwIBTaY-unsplash.jpg",
                            State = "IL",
                            Wifi = true
                        },
                        new
                        {
                            Id = -2,
                            AvailableUnits = 0,
                            City = "Santa Monica",
                            Laundry = true,
                            Name = "A113 Transitional Housing",
                            Photo = "https://angular.io/assets/images/tutorials/faa/brandon-griggs-wR11KBaB86U-unsplash.jpg",
                            State = "CA",
                            Wifi = false
                        },
                        new
                        {
                            Id = -3,
                            AvailableUnits = 1,
                            City = "Juneau",
                            Laundry = false,
                            Name = "Warm Beds Housing Support",
                            Photo = "https://angular.io/assets/images/tutorials/faa/i-do-nothing-but-love-lAyXdl1-Wmc-unsplash.jpg",
                            State = "AK",
                            Wifi = false
                        },
                        new
                        {
                            Id = -4,
                            AvailableUnits = 1,
                            City = "Chicago",
                            Laundry = false,
                            Name = "Homesteady Housing",
                            Photo = "https://angular.io/assets/images/tutorials/faa/ian-macdonald-W8z6aiwfi1E-unsplash.jpg",
                            State = "IL",
                            Wifi = true
                        },
                        new
                        {
                            Id = -5,
                            AvailableUnits = 1,
                            City = "Gary",
                            Laundry = false,
                            Name = "Happy Homes Group",
                            Photo = "https://angular.io/assets/images/tutorials/faa/krzysztof-hepner-978RAXoXnH4-unsplash.jpg",
                            State = "IN",
                            Wifi = true
                        },
                        new
                        {
                            Id = -6,
                            AvailableUnits = 2,
                            City = "Oakland",
                            Laundry = true,
                            Name = "Hopeful Apartment Group",
                            Photo = "https://angular.io/assets/images/tutorials/faa/r-architecture-JvQ0Q5IkeMM-unsplash.jpg",
                            State = "CA",
                            Wifi = true
                        },
                        new
                        {
                            Id = -7,
                            AvailableUnits = 5,
                            City = "Oakland",
                            Laundry = true,
                            Name = "Seriously Safe Towns",
                            Photo = "https://angular.io/assets/images/tutorials/faa/phil-hearing-IYfp2Ixe9nM-unsplash.jpg",
                            State = "CA",
                            Wifi = true
                        },
                        new
                        {
                            Id = -8,
                            AvailableUnits = 2,
                            City = "Oakland",
                            Laundry = true,
                            Name = "Hopeful Housing Solutions",
                            Photo = "https://angular.io/assets/images/tutorials/faa/r-architecture-GGupkreKwxA-unsplash.jpg",
                            State = "CA",
                            Wifi = true
                        },
                        new
                        {
                            Id = -9,
                            AvailableUnits = 10,
                            City = "Oakland",
                            Laundry = false,
                            Name = "Seriously Safe Towns",
                            Photo = "https://angular.io/assets/images/tutorials/faa/saru-robert-9rP3mxf8qWI-unsplash.jpg",
                            State = "CA",
                            Wifi = false
                        },
                        new
                        {
                            Id = -10,
                            AvailableUnits = 6,
                            City = "Portland",
                            Laundry = true,
                            Name = "Capital Safe Towns",
                            Photo = "https://angular.io/assets/images/tutorials/faa/webaliser-_TPTXZd9mOo-unsplash.jpg",
                            State = "OR",
                            Wifi = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
